### ISSUE TITLE
Scripts are not executable when using `exercism download`

### ISSUE THREAD

**Issue by 0xE282B0** [exercism/cobol#45]
Hi,
I was checking out the [cobol track](https://exercism.org/tracks/cobol) as a user and found the following problem on a Mac:
```Bash
> exercism download --exercise=reverse-string --track=cobol
> cd ~/Exercism/cobol/reverse-string
> ./test.sh 
zsh: permission denied: ./test.sh
```

In this git repo the scrips have execute flags, but when using `exercism download` the scripts are not executable.
Has someone experience with scripts from other tracks? Do we need to declare them somewhere as executables?

**Comment by KTSnowy** [comment]
That's weird, it's working in the CI tests so they should still have the executable flag I think.

I'll try running it on my Mac

**Comment by KTSnowy** [comment]
hello-world % ./test.sh
    zsh: permission denied: ./test.sh

I'm getting the same issue on the hello-world exercise on a Mac.

**Comment by KTSnowy** [comment]
@0xE282B0 the test.sh has the executable flag when executing directly from the track repo, but not when downloading from the Exercism CLI

**Comment by axtens** [comment]
So are you executing this in the root of every task?
```
git update-index --chmod=+x ./test.sh 
git update-index --chmod=+x ./bin/fetch-cobolcheck
```
You may well be, and if you are then "Houston, we have a problem!"

**Comment by KTSnowy** [comment]
Wait, are we supported to execute those two commands?

**Comment by axtens** [comment]
I have been

**Comment by 0xE282B0** [comment]
In this repository all the exec flags are fine. To set them with those two commands is very important when you are working on Windows to make the CI work.

However, my problem is that when I'm using the exercism CLI tool, like a student, then I have no exec flags anymore.
I found out, that this behavior is intended and here is a good summary on the discussion: https://github.com/exercism/cli/issues/903#issuecomment-556451115

I can change the scripts that we use `bash test.sh` to start the tests instead of `./test.sh`.
Or we open an issue in the https://github.com/exercism/cli/ repo. Other tracks like ruby or groovy and kotlin, have similar problems.

**Comment by 0xE282B0** [comment]
@KTSnowy the official way to execute a test on a UNIX fs is now `bash test.sh`.
