### ISSUE TITLE
Hamming Distance exercise files not updating on the website

### ISSUE THREAD

**Issue by KTSnowy** [exercism/cobol#58]

**Comment by iHiD** [comment]
_(I've moved this to the cobol repository as I don't think it's got anything to do with the test runner)_

**Comment by KTSnowy** [comment]
@iHiD is it possible that a file in the Hamming exercise is causing this?

**Comment by KTSnowy** [comment]
After merging the empty new line in #59 I can now update the Hamming exercise normally. I have no idea what caused it, but it's working now.
