### ISSUE TITLE
Syntax highlighting: Operators

### ISSUE THREAD

**Issue by joshgoebel** [exercism/cobol#6]
@joshgoebel I can't find a way to make operators work and I can't find any documentation on regex.either( )
But I did fix the keyword pattern, so that's working now.

_Originally posted by @KTSnowy in https://github.com/exercism/cobol/issues/1#issuecomment-1182195885_

---

Maybe show me the last thing you tried?  It's not documented, but look in the `regex.js` source and it should be easy to see - it just takes an arrray of strings or regex - or you can manually write the regex out - it's just nicer to use the helper.

**Comment by KTSnowy** [comment]
![Capture](https://user-images.githubusercontent.com/73310001/178573953-b3ff9c30-db3f-4dd4-b276-2dbc47176ab2.PNG)
Will this work?

**Comment by joshgoebel** [comment]
`match` (sugar for `begin`) is nicer, but yes that should work IF it doesn't need any escaping.  It looks right at a glance.

**Comment by KTSnowy** [comment]
![Capture](https://user-images.githubusercontent.com/73310001/178575499-e4df9e98-5c2d-4a4c-8919-2432ce5ab695.PNG)
Hey @joshgoebel it worked, we now have operator and type highlighting

**Comment by KTSnowy** [comment]
There's one more issue, COBOL comments start with a `*>` and COBOL also has `*` and `>` operators. This means that we'll have to use regex negative lookahead and negative lookbehind, and lookbehind is not supported on Safari.

**Comment by KTSnowy** [comment]
This is to keep the operator regex from overwriting the hljs.COMMENT() regex and not displaying comments properly

**Comment by KTSnowy** [comment]
![Capture](https://user-images.githubusercontent.com/73310001/178590124-0fcd6d4b-ff8e-428c-81b6-4258ecf0f259.PNG)

**Comment by KTSnowy** [comment]
I uploaded the latest version to NPM: https://www.npmjs.com/package/highlightjs-cobol

**Comment by KTSnowy** [comment]
I see that the operator regex also broke the keywords with a -

**Comment by joshgoebel** [comment]
> negative lookbehind, and lookbehind is not supported on Safari.

Yeah, generally we don't recommend anyone use lookbehind (and it's forbidden in core) because of Safari.  There are various tricks, did you figure it out?

Why do you think you need look-behind, for `-`?  Doesn't look-ahead cover comments?

**Comment by KTSnowy** [comment]
I'll try to update it later today without lookbehind if I find a way to make it work.

**Comment by joshgoebel** [comment]
> I can't make it ignore *> in the operator regex without lookahead

Negative lookahead, no?  `* not followed by >`... looking `\*(?!>)`

You can use look-ahead everywhere, the issue is with look-behind (in Safari).

> Is there a way to make highlightjs choose the comment and keyword regex first over the operator regex?

contains rules are scanned in the order specified, but `keywords` is a whole sep engine that runs "inbetween" other things...

> same thing with the keywords and the - operator.

Exactly example please?

**Comment by KTSnowy** [comment]
![178590124-0fcd6d4b-ff8e-428c-81b6-4258ecf0f259](https://user-images.githubusercontent.com/73310001/178604603-c95492a5-86cf-4cd7-abea-0ab856a21476.png)
Here, function-id for example didn't get completely highlighted because it would choose the `-` operator instead of the keyword.

**Comment by joshgoebel** [comment]
I saw originally you were using `\W`, was that not helping?  IF you never need the character before to have it's own highlight you could use a multimatch:

```js
{
match : [ /\W/, /-/ ],
scope: { 1: null, 2: "operator" }
```

Or even multiple multi-matches (for diff cases)... but if you need the content immediately before to match another rule - this trick no longer works.

Otherwise you may need to fall back to specifying a custom match rule for ONLY `-` keywords (or move all your keywords to rules)... once you are just using normal rules you defeat the "weirdness" of the `keywords` engine.  This has performance implications if you have a zillion keywords, but I think your keyboard could would be "ok".  The inbetween ground is to only use rules for the `-` keywords...

See `angelscript` for an example of using rules for keywords... the `keywords` engine is just a lot more convenient if it works...

**Comment by KTSnowy** [comment]
If you'd like to see the test here's the codepen: https://codepen.io/ktsnowy/pen/vYRXxov

**Comment by KTSnowy** [comment]
The negative lookbehind was also removed in version 0.2.11, so it should be all working fine now.

**Comment by joshgoebel** [comment]
>  so requiring a space around the - operator would be best practice anyways.

Oh sure if you can just say "use best practices" and then code for the space that's even simpler! :-)  Awesome.
