### ISSUE TITLE
Syntax highlighting in editor

### ISSUE THREAD

**Issue by 0xE282B0** [exercism/cobol#64]
Hi,
When I look at my submitted exercise the syntax highlighting looks good.
However, when I open the editor it is not working.

![image](https://user-images.githubusercontent.com/4034494/181566763-b36e0bd7-2118-435e-8206-85902eb5e1ac.png)
![image](https://user-images.githubusercontent.com/4034494/181566992-4cdfa7c2-e9fb-4201-88d7-576fd9eebb0b.png)

**Comment by KTSnowy** [comment]
I also noticed this when working on the exercises.

@iHiD @ErikSchierboom 

Is there anything we need to do to enable the highlighter in the editor?

**Comment by ErikSchierboom** [comment]
No, we need to do something: https://github.com/exercism/website/pull/2816
