### ISSUE TITLE
Can't get tests passewd - need help

### ISSUE THREAD

**Issue by SteveHayward** [exercism/cobol#81]
Can't figure out what I'm doing wrong. My code attached for Yacht execise.
[yacht code.txt](https://github.com/exercism/exercism/files/9450254/yacht.code.txt)

**Comment by axtens** [comment]
Please take the attached file, remove the .txt extension, and place in your tst/yacht folder replacing the .cut file that exists there. 

This demonstrates how to comment out tests. I have left the first test uncommented. As you implement your logic, remove the comments from each testcase until you are able to get through the full set.

[yacht.cut.txt](https://github.com/exercism/cobol/files/9474352/yacht.cut.txt)

**Comment by axtens** [comment]
One more thing. Can you describe to me the _process_ you intend to follow to establish whether a roll is a big straight or a small straight? Use English words rather than going straight into code. A lot programming is problem-solving: until you can adequately describe the problem, the solution remains largely distant.

**Comment by axtens** [comment]
The reason I ask is that you've got 
```
         IF STRAIGHT
            IF ROLL-BY-DIE = 111110 OR 011111
            COMPUTE WS-RESULT = 30 GO TO DONE.
```
How are you building ROLL-BY-DIE? Why are you using a six-element array and what is it representing?

**Comment by SteveHayward** [comment]
1 You asked, " Can you describe to me the process you intend to follow to establish whether a roll is a big straight or a small straight?" The answer is I need to correct my code:distinguish between 

88 STRAIGHT VALUE "little straight" OR "big straight".becomes 

88 BIG-STRAIGHT VALUE "big straight" 


88 LITTLE-STRAIGHT VALUE "little straight" 


I thought of combining them since the scores for both were 30. 
2 ROLL-BY-DIE, 6- element array, represents the number of times each die value occurs for a roll. E.g., array is 112010 for a roll of 23351.

**Comment by axtens** [comment]
Wow, that's a cool way of approaching it. 

When I was doing the task myself, I took a completely different tack, sorting the dice into lowest-to-highest order. Thus there had to be 2 of the first and 3 of the last, or 3 of the first and 2 of the last, for it to be a full-house.

Your way is still going to take a bit of work to enumerate all the full-house possibilities, e.g.
320000, 230000, 302000, 203000, 300200, 200300 ... 032000 ... 000032 etc, so you'll then have to come up with a way of detecting 23 and 32 without having to enumerate all the zeroes in the pattern. (Thinking out loud) maybe inspecting the ROLL-BY-DIE tallying 0 2 and 3 and then accepting everything that has 4 zeroes, one 3 and one 2.

**Comment by axtens** [comment]
How did you get on? I had a go at solving this one using your approach. The overall code size shrank by abouit 80% compared to my sorting approach. I'm happy to share the code with you if you want.

-- Bruce

**Comment by SteveHayward** [comment]
Yep, would like to see your code. Then I should close this one. 
Steve

**Comment by axtens** [comment]
```
       IDENTIFICATION DIVISION.
       PROGRAM-ID. YACHT.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-CATEGORY PIC X(15).
       01 WS-DICE PIC 9(5).
       01 ROLL-COUNTERS PIC 9(6).
       01 ROLL-COUNTER REDEFINES ROLL-COUNTERS.
        03 ROLL-COUNT PIC 9 OCCURS 6 TIMES INDEXED BY ROLL-INDEX.
       01 POINT-COUNT PIC 9.
       01 THREE-ROLLED PIC 9.
       01 TWO-ROLLED PIC 9.
       01 ROLL-LOOP PIC 9.
       01 WS-RESULT PIC 99 VALUE 0.
       PROCEDURE DIVISION.
       YACHT.
         MOVE ZEROES TO WS-RESULT.
         PERFORM COUNT-POINTS.
         EVALUATE WS-CATEGORY
           WHEN 'ones'
            MULTIPLY ROLL-COUNT(1) BY 1 GIVING WS-RESULT
           WHEN 'twos'
            MULTIPLY ROLL-COUNT(2) BY 2 GIVING WS-RESULT
           WHEN 'threes'
            MULTIPLY ROLL-COUNT(3) BY 3 GIVING WS-RESULT
           WHEN 'fours'
            MULTIPLY ROLL-COUNT(4) BY 4 GIVING WS-RESULT
           WHEN 'fives'
            MULTIPLY ROLL-COUNT(5) BY 5 GIVING WS-RESULT
           WHEN 'sixes'
            MULTIPLY ROLL-COUNT(6) BY 6 GIVING WS-RESULT
           WHEN 'little straight'
            IF ROLL-COUNTERS = 111110
             MOVE 30 TO WS-RESULT
            END-IF
           WHEN 'big straight'
            IF ROLL-COUNTERS = 011111
             MOVE 30 TO WS-RESULT
            END-IF
           WHEN 'four of a kind'
             PERFORM VARYING ROLL-LOOP FROM 1 BY 1 UNTIL ROLL-LOOP > 6
              SET ROLL-INDEX TO ROLL-LOOP
              IF ROLL-COUNT(ROLL-INDEX) >= 4 
               MULTIPLY ROLL-LOOP BY 4 GIVING WS-RESULT
              END-IF
             END-PERFORM 
            WHEN 'full house'
             MOVE ZEROES TO THREE-ROLLED
             MOVE ZEROES TO TWO-ROLLED
             PERFORM VARYING ROLL-LOOP FROM 1 BY 1 UNTIL ROLL-LOOP > 6
              SET ROLL-INDEX TO ROLL-LOOP
              IF ROLL-COUNT(ROLL-INDEX) = 3 
               MOVE ROLL-LOOP TO THREE-ROLLED
              END-IF
              IF ROLL-COUNT(ROLL-INDEX) = 2
               MOVE ROLL-LOOP TO TWO-ROLLED
              END-IF
             END-PERFORM 
             IF TWO-ROLLED NOT = ZEROES AND THREE-ROLLED NOT = ZEROES
              COMPUTE WS-RESULT = TWO-ROLLED * 2 + THREE-ROLLED * 3
             END-IF
           WHEN 'choice'
            COMPUTE WS-RESULT = ROLL-COUNT(1) * 1 +
             ROLL-COUNT(2) * 2 +
             ROLL-COUNT(3) * 3 +
             ROLL-COUNT(4) * 4 +
             ROLL-COUNT(5) * 5 +
             ROLL-COUNT(6) * 6 
           WHEN 'yacht'
             IF ROLL-COUNT(1) = 5 OR 
                ROLL-COUNT(2) = 5 OR 
                ROLL-COUNT(3) = 5 OR 
                ROLL-COUNT(4) = 5 OR 
                ROLL-COUNT(5) = 5 OR 
                ROLL-COUNT(6) = 5 
                 MOVE 50 TO WS-RESULT
             END-IF 
         END-EVALUATE.
       YACHT-EXIT.
         EXIT.
       
       COUNT-POINTS.
         PERFORM VARYING ROLL-LOOP FROM 1 BY 1 UNTIL ROLL-LOOP > 6
          MOVE ZEROES TO POINT-COUNT
          SET ROLL-INDEX TO ROLL-LOOP
          INSPECT WS-DICE TALLYING POINT-COUNT FOR ALL ROLL-LOOP
          MOVE POINT-COUNT TO ROLL-COUNT(ROLL-INDEX) 
         END-PERFORM.
       COUNT-POINTS-EXIT.
        EXIT.
 ```

**Comment by SteveHayward** [comment]
Thanks. I really like your organization as applied to this problem. it's very clear. I've marked YACHT as complete. 


I'll be on and off for fiuture problems as I've started a course on Rust and I'm going to try to keep both progressing. 


Again, thanks for your help. 


Stevve

**Comment by axtens** [comment]
Anytime. Glad to be of assistance.

Bruce
