### ISSUE TITLE
Bob exercise start point lacks a Procedural Division 

### ISSUE THREAD

**Issue by ChrisCookOC** [exercism/cobol#84]
Just wondering if this is intentional or not :)

**Comment by axtens** [comment]
I would expect that it's a mistake. However, the code in the src folder is supposed to be just enough to get you going and no more. 

Bottom line: I'm delighted that you know enough cobol to realize that something's missing.

**Comment by axtens** [comment]
The starting point doesn't have to be functional to be a starting point
